library(limma)
library(edgeR)
setwd("~/project/PIRCh-seq/pirch_rpkm/include_intron/raw_reads/v65/")
count=read.table("v65_rpkm_raw_python_norm.txt",sep="\t",header=TRUE,row.names=1,stringsAsFactors=FALSE)
counts=count[,c(1,2,5:18)]
dge <- DGEList(counts = counts)
group_list <- factor(c(rep("Input",2), rep("H3",2), rep("H3K4me1",2), rep("H3K4me3",2), rep("H3K27ac",2), rep("H4K16ac",2), rep("H3K27me3",2), rep("H3K9me3",2)), levels=c("Input", "H3", "H3K4me1", "H3K4me3", "H3K27ac", "H4K16ac", "H3K27me3", "H3K9me3"))
design <- model.matrix(~0+group_list)
colnames(design) <- levels(group_list)
rownames(design) <- colnames(counts)
contrast.matrix <- makeContrasts(H3-Input,H3K4me1-Input,H3K4me3-Input,H3K27ac-Input,H3K27me3-Input,H3K9me3-Input,H4K16ac-Input,levels=design)
keep.exprs <- filterByExpr(dge,group=group_list)
dge <- dge[keep.exprs,, keep.lib.sizes=FALSE]
#dge <- calcNormFactors(dge)
logCPM <- voom(dge, design, plot=TRUE,normalize="quantile")
fit <- lmFit(logCPM, design)
fit2 <- contrasts.fit(fit, contrast.matrix)
fit2 <- eBayes(fit2, trend=TRUE)
output <- topTable(fit2, coef=1,n=Inf)
write.table(output,"./limma_H3_filter.txt", sep="\t", row.names=TRUE, quote=FALSE)
output <- topTable(fit2, coef=2,n=Inf)
write.table(output,"./limma_H3K4me1_filter.txt", sep="\t", row.names=TRUE, quote=FALSE)
output <- topTable(fit2, coef=3,n=Inf)
write.table(output,"./limma_H3K4me3_filter.txt", sep="\t", row.names=TRUE, quote=FALSE)
output <- topTable(fit2, coef=4,n=Inf)
write.table(output,"./limma_H3K27ac_filter.txt", sep="\t", row.names=TRUE, quote=FALSE)
output <- topTable(fit2, coef=5,n=Inf)
write.table(output,"./limma_H3K27me3_filter.txt", sep="\t", row.names=TRUE, quote=FALSE)
output <- topTable(fit2, coef=6,n=Inf)
write.table(output,"./limma_H3K9me3_filter.txt", sep="\t", row.names=TRUE, quote=FALSE)
output <- topTable(fit2, coef=7,n=Inf)
write.table(output,"./limma_H4K16ac_filter.txt", sep="\t", row.names=TRUE, quote=FALSE)
#h3
counts=count[,c(1,2,5,6)]
dge <- DGEList(counts = counts)
dge <- calcNormFactors(dge)
logCPM <- cpm(dge, log=TRUE, prior.count=3)
group_list <- factor(c(rep("Input",2), rep("H3",2)))
design <- model.matrix(~0+group_list)
colnames(design) <- levels(group_list)
rownames(design) <- colnames(counts)
fit <- lmFit(logCPM, design)
contrast.matrix <- makeContrasts(H3-Input, levels=design)
fit2 <- contrasts.fit(fit, contrast.matrix)
fit2 <- eBayes(fit2, trend=TRUE)
output <- topTable(fit2, coef=1,n=Inf)
write.table(output,"./limma_H3_retest.txt", sep="\t", row.names=TRUE, quote=FALSE)

#h3k4me1
counts=count[,c(1,2,7,8)]
dge <- DGEList(counts = counts)
dge <- calcNormFactors(dge)
logCPM <- cpm(dge, log=TRUE, prior.count=3)
group_list <- factor(c(rep("Input",2), rep("H3k4me1",2)))
design <- model.matrix(~group_list)
colnames(design) <- levels(group_list)
rownames(design) <- colnames(counts)
fit <- lmFit(logCPM, design)
fit <- eBayes(fit, trend=TRUE)
output <- topTable(fit, coef=2,n=Inf)
write.table(output,"./limma_H3k4me1.txt", sep="\t", row.names=TRUE, quote=FALSE)

#h3k4me3
counts=count[,c(1,2,9,10)]
dge <- DGEList(counts = counts)
dge <- calcNormFactors(dge)
logCPM <- cpm(dge, log=TRUE, prior.count=3)
group_list <- factor(c(rep("Input",2), rep("H3k4me3",2)))
design <- model.matrix(~group_list)
colnames(design) <- levels(group_list)
rownames(design) <- colnames(counts)
fit <- lmFit(logCPM, design)
fit <- eBayes(fit, trend=TRUE)
output <- topTable(fit, coef=2,n=Inf)
write.table(output,"./limma_H3k4me3.txt", sep="\t", row.names=TRUE, quote=FALSE)

#h3k27ac_2
counts=count[,c(1,2,11,12)]
dge <- DGEList(counts = counts)
dge <- calcNormFactors(dge)
logCPM <- cpm(dge, log=TRUE, prior.count=3)
group_list <- factor(c(rep("Input",2), rep("H3k27ac",2)))
design <- model.matrix(~group_list)
colnames(design) <- levels(group_list)
rownames(design) <- colnames(counts)
fit <- lmFit(logCPM, design)
fit <- eBayes(fit, trend=TRUE)
output <- topTable(fit, coef=2,n=Inf)
write.table(output,"./limma_H3k27ac_2.txt", sep="\t", row.names=TRUE, quote=FALSE)

#h3k27ac_1
counts=count[,c(1,2,12)]
dge <- DGEList(counts = counts)
dge <- calcNormFactors(dge)
logCPM <- cpm(dge, log=TRUE, prior.count=3)
group_list <- factor(c(rep("Input",2), rep("H3k27ac",1)))
design <- model.matrix(~group_list)
colnames(design) <- levels(group_list)
rownames(design) <- colnames(counts)
fit <- lmFit(logCPM, design)
fit <- eBayes(fit, trend=TRUE)
output <- topTable(fit, coef=2,n=Inf)
write.table(output,"./limma_H3k27ac_1.txt", sep="\t", row.names=TRUE, quote=FALSE)

#h3k27me3
counts=count[,c(1,2,15,16)]
dge <- DGEList(counts = counts)
dge <- calcNormFactors(dge)
logCPM <- cpm(dge, log=TRUE, prior.count=3)
group_list <- factor(c(rep("Input",2), rep("H3k27me3",2)))
design <- model.matrix(~group_list)
colnames(design) <- levels(group_list)
rownames(design) <- colnames(counts)
fit <- lmFit(logCPM, design)
fit <- eBayes(fit, trend=TRUE)
output <- topTable(fit, coef=2,n=Inf)
write.table(output,"./limma_H3k27me3.txt", sep="\t", row.names=TRUE, quote=FALSE)

#h3k9me3
counts=count[,c(1,2,17,18)]
dge <- DGEList(counts = counts)
dge <- calcNormFactors(dge)
logCPM <- cpm(dge, log=TRUE, prior.count=3)
group_list <- factor(c(rep("Input",2), rep("H3k9me3",2)))
design <- model.matrix(~group_list)
colnames(design) <- levels(group_list)
rownames(design) <- colnames(counts)
fit <- lmFit(logCPM, design)
fit <- eBayes(fit, trend=TRUE)
output <- topTable(fit, coef=2,n=Inf)
write.table(output,"./limma_H3k9me3.txt", sep="\t", row.names=TRUE, quote=FALSE)

#h4k16ac
counts=count[,c(1,2,13,14)]
dge <- DGEList(counts = counts)
dge <- calcNormFactors(dge)
logCPM <- cpm(dge, log=TRUE, prior.count=3)
group_list <- factor(c(rep("Input",2), rep("H4k16ac",2)))
design <- model.matrix(~group_list)
colnames(design) <- levels(group_list)
rownames(design) <- colnames(counts)
fit <- lmFit(logCPM, design)
fit <- eBayes(fit, trend=TRUE)
output <- topTable(fit, coef=2,n=Inf)
write.table(output,"./limma_H4k16ac.txt", sep="\t", row.names=TRUE, quote=FALSE)
